// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnkkgjmudteyzzfbogto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhua2tnam11ZHRleXp6ZmJvZ3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODc5MDYsImV4cCI6MjA3MDk2MzkwNn0.GfKIbQUcov6XqSv6ca5qJiq6NsaR7i_xc_OGbUnydH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});